apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.apps.name }}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    path: apps/{{ .Values.apps.name }}
  destination:
    server: {{ .Values.destination.server }}
    namespace: {{ .Values.destination.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{ range .Values.apps }}
---
{{ end }}