apps:
  - name: grafana
  - name: my-app
repoURL: https://github.com/nicanorfinance/nnf-k8s-app-of-apps.git
targetRevision: main
destination:
  server: https://kubernetes.default.svc
  namespace: default
