prometheus:
  service:
    type: ClusterIP
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}
    replicas: 1  # Single server pod
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
  nodeExporter:
    enabled: true
    podAntiAffinity: {}  # Disable anti-affinity for node-exporter