prometheus:
  service:
    type: ClusterIP
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}
    replicas: 1
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
  nodeExporter:
    enabled: true
    podAntiAffinity: {}  # Disable anti-affinity
  alertmanager:
    resources:
      requests:
        cpu: "50m"
        memory: "100Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"